apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcp-agent-cronjob
  namespace: mcp-agent
spec:
  # Run every day at 2 AM (adjust as needed for testing)
  schedule: "0 2 * * *"
  # For testing, you can use "*/5 * * * *" to run every 5 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mcp-agent-cronjob
        spec:
          containers:
          - name: mcp-agent
            image: wholelottahoopla/rarb:latest
            imagePullPolicy: Always
            command: ["node", "index.js"]
            args:
              - "--url"
              - "$(MCP_URL)"
              - "--model"
              - "$(MODEL)"
              - "--max-steps"
              - "$(MAX_STEPS)"
              - "--headless"
              - "--prompt"
              - "go to craigslist and find free things in sf posted today and write to /output/items.csv only include interesting things, include the urls"
            env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-agent-secrets
                  key: OPENAI_API_KEY
            - name: MCP_URL
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MCP_URL
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MODEL
            - name: MAX_STEPS
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MAX_STEPS
            - name: NODE_ENV
              value: "production"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: output
              mountPath: /output
          volumes:
          - name: tmp
            emptyDir: {}
          - name: output
            emptyDir: {}
          restartPolicy: OnFailure
