apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcp-agent-cronjob
  namespace: default
spec:
  # Run every 5 minutes for testing (change to "0 2 * * *" for daily at 2 AM)
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false  # Set to true to pause
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mcp-agent-cronjob
        spec:
          containers:
          - name: mcp-agent
            image: wholelottahoopla/rarb:latest
            imagePullPolicy: Always
            command: ["node", "index.js"]
            args:
              - "--url"
              - "$(MCP_URL)"
              - "--model"
              - "$(MODEL)"
              - "--max-steps"
              - "$(MAX_STEPS)"
              - "--headless"
              - "--prompt"
              - "go to craigslist and find free things in sf posted today and then write the info to a csv in /output/items.csv only include interesting things, if its junk i don't care. include the urls in the output. if already in items.csv don't include it twice. url for sf free stuff is https://sfbay.craigslist.org/search/zip#search=2~gallery~0"
            env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-agent-secrets-test
                  key: OPENAI_API_KEY
            - name: MCP_URL
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MCP_URL
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MODEL
            - name: MAX_STEPS
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: MAX_STEPS
            - name: NODE_ENV
              value: "production"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: output
              mountPath: /output
          volumes:
          - name: tmp
            emptyDir: {}
          - name: output
            emptyDir: {}
          restartPolicy: OnFailure
