apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-agent
  namespace: mcp-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-agent
  template:
    metadata:
      labels:
        app: mcp-agent
    spec:
      containers:
      - name: mcp-agent
        image: wholelottahoopla/rarb:latest
        imagePullPolicy: Always
        command: ["node", "index.js"]
        args:
          - "--url"
          - "$(MCP_URL)"
          - "--model"
          - "$(MODEL)"
          - "--max-steps"
          - "$(MAX_STEPS)"
          - "--headless"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-agent-secrets
              key: OPENAI_API_KEY
        - name: MCP_URL
          valueFrom:
            configMapKeyRef:
              name: mcp-agent-config
              key: MCP_URL
        - name: MODEL
          valueFrom:
            configMapKeyRef:
              name: mcp-agent-config
              key: MODEL
        - name: MAX_STEPS
          valueFrom:
            configMapKeyRef:
              name: mcp-agent-config
              key: MAX_STEPS
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: output
          mountPath: /output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: output
        emptyDir: {}
      restartPolicy: Always
