apiVersion: v1
kind: Service
metadata:
  name: mcp-agent
  namespace: mcp-agent
spec:
  selector:
    app: mcp-agent
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
